<?php

namespace Database\Seeders;

use App\Models\CommunityPartnerships;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CommunityPartnershipsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $partnerships = [
            [1,'Inspektorat Kota Pontianak'],
            [1,'Kantor Kecamatan Pemberdayaan Pontianak'],
            [1,'Inspektorat Kota Pontianak'],
            [1,'Inspektorat Kota Pontianak'],
            [1,'Pemerintah Kota Pontianak - Dinas Pendidikan  site.co.id+1'],
            [1,'Sekretariat Daerah Kota Pontianak - Bagian Kebersihan'],
            [1,'Sekretariat Daerah Kota Pontianak - Bagian Kebersihan'],
            [1,'Bappeda Kota Pontianak'],
            [1,'Kantor Kecamatan Pendidikan Pontianak  Wikipedia'],
            [1,'Dinas Kesehatan Kota Pontianak - Puskesmas Kebersihan  Instagram+1'],
            [1,'Bappeda Kota Pontianak'],
            [1,'Pemerintah Kota Pontianak - Dinas PMK'],
            [1,'Inspektorat Kota Pontianak'],
            [1,'Pemerintah Kota Pontianak - Dinas Pendidikan  Instagram+1'],
            [1,'Dinas Kependudukan dan Pencatatan Sipil Pontianak'],
            [1,'Dinas Kependudukan dan Pencatatan Sipil Pontianak'],
            [1,'Sekretariat Daerah Kota Pontianak - Bagian Pemberdayaan  IDalamat.com+1'],
            [1,'Pemerintah Kota Pontianak - Dinas Lingkungan Hidup  Instagram+1'],
            [1,'Kantor Kecamatan PMK Pontianak'],
            [1,'Bappeda Kota Pontianak'],
            [1,'Sekretariat Daerah Kota Pontianak - Bagian Lingkungan Hidup'],
            [1,'Pemerintah Kota Pontianak - Dinas Perhubungan  IDalamat.com+1'],
            [1,'Sekretariat Daerah Kota Pontianak - Bagian Perhubungan'],
            [1,'Kantor Satpol PP Pontianak'],
            [1,'Kantor Kecamatan Pemberdayaan Pontianak  site.co.id+1'],
            [1,'Dinas Kependudukan dan Pencatatan Sipil Pontianak'],
            [1,'Bappeda Kota Pontianak  Wikipedia'],
            [1,'Pemerintah Kota Pontianak - Dinas Kebersihan'],
            [1,'Dinas Kependudukan dan Pencatatan Sipil Pontianak'],
            [1,'Dinas Kependudukan dan Pencatatan Sipil Pontianak'],
            [1,'Kantor Kecamatan Perhubungan Pontianak'],
            [1,'Dinas Kesehatan Kota Pontianak - Puskesmas Pendidikan'],
            [1,'Kantor Satpol PP Pontianak'],
            [1,'Kantor Kecamatan Pendidikan Pontianak'],
            [1,'Pemerintah Kota Pontianak - Dinas Pemberdayaan'],
            [1,'Pemerintah Kota Pontianak - Dinas Lingkungan Hidup  IDalamat.com+1'],
            [1,'Inspektorat Kota Pontianak  site.co.id+1'],
            [1,'Dinas Kependudukan dan Pencatatan Sipil Pontianak'],
            [1,'Dinas Kependudukan dan Pencatatan Sipil Pontianak'],
            [1,'Dinas Kependudukan dan Pencatatan Sipil Pontianak'],
            [1,'Dinas Kependudukan dan Pencatatan Sipil Pontianak'],
            [1,'Sekretariat Daerah Kota Pontianak - Bagian Kebersihan'],
            [1,'Dinas Kependudukan dan Pencatatan Sipil Pontianak'],
            [1,'Dinas Kesehatan Kota Pontianak - Puskesmas Lingkungan Hidup  Wikipedia'],
            [1,'Inspektorat Kota Pontianak  Wikipedia'],
            [1,'Dinas Kesehatan Kota Pontianak - Puskesmas Pendidikan'],
            [1,'Kantor Satpol PP Pontianak'],
            [1,'Kantor Kecamatan Kebersihan Pontianak  Wikipedia'],
            [1,'Kantor Kecamatan Lingkungan Hidup Pontianak'],
            [1,'Dinas Kependudukan dan Pencatatan Sipil Pontianak  site.co.id+1'],
            [1,'Pemerintah Kota Pontianak - Dinas Pemberdayaan  Facebook+1'],
            [1,'Dinas Kesehatan Kota Pontianak - Puskesmas Lingkungan Hidup'],
            [1,'Kantor Kecamatan Pendidikan Pontianak  Instagram+1'],
            [1,'Bappeda Kota Pontianak'],
            [1,'Pemerintah Kota Pontianak - Dinas Pendidikan  Instagram+1'],
            [1,'Bappeda Kota Pontianak'],
            [1,'Dinas Kesehatan Kota Pontianak - Puskesmas PMK'],
            [1,'Dinas Kesehatan Kota Pontianak - Puskesmas Lingkungan Hidup'],
            [1,'Sekretariat Daerah Kota Pontianak - Bagian Pemberdayaan'],
            [1,'Inspektorat Kota Pontianak'],
            [1,'Dinas Kependudukan dan Pencatatan Sipil Pontianak'],
            [1,'Sekretariat Daerah Kota Pontianak - Bagian Lingkungan Hidup  site.co.id+1'],
            [1,'Kantor Kecamatan Perhubungan Pontianak'],
            [1,'Sekretariat Daerah Kota Pontianak - Bagian Kebersihan'],
            [1,'Inspektorat Kota Pontianak'],
            [1,'Bappeda Kota Pontianak'],
            [1,'Bappeda Kota Pontianak'],
            [1,'Inspektorat Kota Pontianak'],
            [1,'Sekretariat Daerah Kota Pontianak - Bagian Kebersihan'],
            [1,'Bappeda Kota Pontianak'],
            [1,'Kantor Satpol PP Pontianak'],
            [1,'Bappeda Kota Pontianak'],
            [1,'Dinas Kesehatan Kota Pontianak - Puskesmas Kebersihan'],
            [1,'Kantor Kecamatan Perhubungan Pontianak'],
            [1,'Kantor Kecamatan PMK Pontianak  site.co.id+1'],
            [1,'Pemerintah Kota Pontianak - Dinas PMK'],
            [1,'Dinas Kesehatan Kota Pontianak - Puskesmas Lingkungan Hidup'],
            [1,'Bappeda Kota Pontianak'],
            [1,'Kantor Satpol PP Pontianak  Instagram+1'],
            [1,'Kantor Satpol PP Pontianak'],
            [1,'Dinas Kesehatan Kota Pontianak - Puskesmas Perhubungan'],
            [1,'Pemerintah Kota Pontianak - Dinas Kebersihan'],
            [1,'Pemerintah Kota Pontianak - Dinas PMK'],
            [1,'Kantor Kecamatan Perhubungan Pontianak'],
            [1,'Kantor Satpol PP Pontianak'],
            [1,'Bappeda Kota Pontianak'],
            [1,'Inspektorat Kota Pontianak'],
            [1,'Kantor Kecamatan Perhubungan Pontianak'],
            [1,'Inspektorat Kota Pontianak'],
            [1,'Sekretariat Daerah Kota Pontianak - Bagian Pemberdayaan'],
            [1,'Pemerintah Kota Pontianak - Dinas Lingkungan Hidup'],
            [1,'Kantor Satpol PP Pontianak'],
            [1,'Kantor Satpol PP Pontianak'],
            [1,'Kantor Satpol PP Pontianak'],
            [1,'Inspektorat Kota Pontianak'],
            [1,'Sekretariat Daerah Kota Pontianak - Bagian Perhubungan'],
            [1,'Sekretariat Daerah Kota Pontianak - Bagian Perhubungan  Instagram+1'],
            [1,'Kantor Satpol PP Pontianak'],
            [1,'Dinas Kependudukan dan Pencatatan Sipil Pontianak'],
            [1,'Sekretariat Daerah Kota Pontianak - Bagian Pemberdayaan'],
            [1,'Kantor Satpol PP Pontianak'],
            [1,'Dinas Kesehatan Kota Pontianak - Puskesmas Pemberdayaan'],
            [1,'Kantor Kecamatan Pendidikan Pontianak'],
            [1,'Dinas Kependudukan dan Pencatatan Sipil Pontianak'],
            [1,'Inspektorat Kota Pontianak'],
            [1,'Inspektorat Kota Pontianak'],
            [1,'Bappeda Kota Pontianak'],
            [1,'Dinas Kependudukan dan Pencatatan Sipil Pontianak'],
            [1,'Kantor Satpol PP Pontianak'],
            [1,'Kantor Kecamatan Kebersihan Pontianak  site.co.id+1'],
            [1,'Kantor Satpol PP Pontianak  site.co.id+1'],
            [1,'Kantor Satpol PP Pontianak'],
            [2,'Akademi Keperawatan Pontianak Manajemen'],
            [2,'Akademi Keperawatan Pontianak Manajemen  Instagram+1'],
            [2,'Universitas Tanjungpura Fakultas Ekonomi'],
            [2,'Sekolah Tinggi Ilmu Ekonomi Pontianak - Program Sistem Informasi'],
            [2,'Sekolah Tinggi Ilmu Ekonomi Pontianak - Program Ekonomi'],
            [2,'Universitas PGRI Pontianak - Jurusan Kedokteran'],
            [2,'Sekolah Tinggi Ilmu Ekonomi Pontianak - Program Manajemen  IDalamat.com+1'],
            [2,'Universitas PGRI Pontianak - Jurusan Manajemen  Facebook+1'],
            [2,'Institut Manajemen Pontianak'],
            [2,'Universitas PGRI Pontianak - Jurusan Ekonomi'],
            [2,'Politeknik Negeri Pontianak Program Studi Teknik'],
            [2,'Universitas Tanjungpura Fakultas Manajemen'],
            [2,'Politeknik Negeri Pontianak Program Studi Teknik'],
            [2,'Institut Teknik Pontianak  site.co.id+1'],
            [2,'Universitas Tanjungpura Fakultas Hukum'],
            [2,'Institut Keguruan Pontianak  Instagram+1'],
            [2,'Institut Teknik Pontianak'],
            [2,'Universitas Tanjungpura Fakultas Manajemen'],
            [2,'Institut Sistem Informasi Pontianak  IDalamat.com+1'],
            [2,'Universitas Tanjungpura Fakultas Teknik  IDalamat.com+1'],
            [2,'Universitas Tanjungpura Fakultas Teknik'],
            [2,'Sekolah Tinggi Ilmu Ekonomi Pontianak - Program Hukum'],
            [2,'Politeknik Negeri Pontianak Program Studi Teknik'],
            [2,'Universitas Tanjungpura Fakultas Teknik'],
            [2,'Institut Kedokteran Pontianak'],
            [2,'Akademi Keperawatan Pontianak Manajemen'],
            [2,'Universitas PGRI Pontianak - Jurusan Ekonomi'],
            [2,'Institut Ekonomi Pontianak'],
            [2,'Universitas Tanjungpura Fakultas Ekonomi'],
            [2,'Politeknik Negeri Pontianak Program Studi Kedokteran  Instagram+1'],
            [2,'Akademi Keperawatan Pontianak Ekonomi'],
            [2,'Sekolah Tinggi Ilmu Ekonomi Pontianak - Program Ekonomi'],
            [2,'Universitas PGRI Pontianak - Jurusan Sistem Informasi'],
            [2,'Sekolah Tinggi Ilmu Ekonomi Pontianak - Program Kedokteran  Facebook+1'],
            [2,'Politeknik Negeri Pontianak Program Studi Hukum'],
            [2,'Universitas PGRI Pontianak - Jurusan Hukum'],
            [2,'Universitas PGRI Pontianak - Jurusan Sistem Informasi'],
            [2,'Akademi Keperawatan Pontianak Hukum'],
            [2,'Sekolah Tinggi Ilmu Ekonomi Pontianak - Program Keguruan  Facebook+1'],
            [2,'Universitas PGRI Pontianak - Jurusan Keguruan'],
            [2,'Institut Kedokteran Pontianak'],
            [2,'Universitas PGRI Pontianak - Jurusan Hukum  Instagram+1'],
            [2,'Sekolah Tinggi Ilmu Ekonomi Pontianak - Program Teknik  IDalamat.com+1'],
            [2,'Institut Kedokteran Pontianak  Wikipedia'],
            [2,'Universitas Tanjungpura Fakultas Keguruan'],
            [2,'Politeknik Negeri Pontianak Program Studi Ekonomi'],
            [2,'Universitas PGRI Pontianak - Jurusan Ekonomi'],
            [2,'Institut Teknik Pontianak'],
            [2,'Institut Manajemen Pontianak'],
            [2,'Institut Kedokteran Pontianak  Wikipedia'],
            [2,'Institut Ekonomi Pontianak'],
            [2,'Sekolah Tinggi Ilmu Ekonomi Pontianak - Program Sistem Informasi'],
            [2,'Sekolah Tinggi Ilmu Ekonomi Pontianak - Program Keguruan'],
            [2,'Universitas Tanjungpura Fakultas Hukum'],
            [2,'Universitas Tanjungpura Fakultas Sistem Informasi'],
            [2,'Akademi Keperawatan Pontianak Teknik'],
            [2,'Akademi Keperawatan Pontianak Kedokteran'],
            [2,'Sekolah Tinggi Ilmu Ekonomi Pontianak - Program Keguruan'],
            [2,'Institut Teknik Pontianak'],
            [2,'Universitas PGRI Pontianak - Jurusan Teknik'],
            [2,'Universitas PGRI Pontianak - Jurusan Ekonomi  IDalamat.com+1'],
            [2,'Universitas Tanjungpura Fakultas Manajemen'],
            [2,'Universitas PGRI Pontianak - Jurusan Kedokteran  Instagram+1'],
            [2,'Akademi Keperawatan Pontianak Ekonomi'],
            [2,'Akademi Keperawatan Pontianak Hukum'],
            [2,'Politeknik Negeri Pontianak Program Studi Manajemen  Wikipedia'],
            [2,'Akademi Keperawatan Pontianak Kedokteran  Wikipedia'],
            [2,'Universitas PGRI Pontianak - Jurusan Manajemen'],
            [2,'Institut Sistem Informasi Pontianak'],
            [2,'Politeknik Negeri Pontianak Program Studi Ekonomi'],
            [2,'Akademi Keperawatan Pontianak Hukum  Instagram+1'],
            [2,'Universitas Tanjungpura Fakultas Manajemen'],
            [2,'Sekolah Tinggi Ilmu Ekonomi Pontianak - Program Hukum'],
            [2,'Akademi Keperawatan Pontianak Manajemen'],
            [2,'Institut Manajemen Pontianak'],
            [2,'Akademi Keperawatan Pontianak Teknik'],
            [2,'Sekolah Tinggi Ilmu Ekonomi Pontianak - Program Sistem Informasi  Instagram+1'],
            [2,'Institut Keguruan Pontianak  Instagram+1'],
            [2,'Universitas PGRI Pontianak - Jurusan Ekonomi'],
            [2,'Politeknik Negeri Pontianak Program Studi Keguruan  Wikipedia'],
            [2,'Universitas PGRI Pontianak - Jurusan Hukum  Wikipedia'],
            [2,'Politeknik Negeri Pontianak Program Studi Manajemen'],
            [2,'Institut Hukum Pontianak'],
            [2,'Sekolah Tinggi Ilmu Ekonomi Pontianak - Program Ekonomi'],
            [2,'Akademi Keperawatan Pontianak Ekonomi'],
            [2,'Universitas PGRI Pontianak - Jurusan Manajemen'],
            [2,'Universitas PGRI Pontianak - Jurusan Sistem Informasi'],
            [2,'Akademi Keperawatan Pontianak Hukum'],
            [2,'Institut Kedokteran Pontianak'],
            [2,'Sekolah Tinggi Ilmu Ekonomi Pontianak - Program Manajemen  Instagram+1'],
            [2,'Universitas Tanjungpura Fakultas Hukum  Wikipedia'],
            [2,'Universitas PGRI Pontianak - Jurusan Manajemen'],
            [2,'Institut Manajemen Pontianak  Wikipedia'],
            [2,'Politeknik Negeri Pontianak Program Studi Sistem Informasi'],
            [2,'Sekolah Tinggi Ilmu Ekonomi Pontianak - Program Ekonomi'],
            [2,'Institut Manajemen Pontianak'],
            [2,'Akademi Keperawatan Pontianak Hukum'],
            [2,'Akademi Keperawatan Pontianak Teknik'],
            [2,'Universitas PGRI Pontianak - Jurusan Teknik'],
            [2,'Institut Hukum Pontianak'],
            [2,'Universitas PGRI Pontianak - Jurusan Keguruan'],
            [2,'Universitas Tanjungpura Fakultas Hukum  Wikipedia'],
            [2,'Institut Sistem Informasi Pontianak  Wikipedia'],
            [2,'Sekolah Tinggi Ilmu Ekonomi Pontianak - Program Ekonomi'],
            [2,'Politeknik Negeri Pontianak Program Studi Teknik'],
            [2,'Sekolah Tinggi Ilmu Ekonomi Pontianak - Program Hukum'],
            [2,'Akademi Keperawatan Pontianak Sistem Informasi  site.co.id+1'],
            [2,'Politeknik Negeri Pontianak Program Studi Keguruan'],
            [2,'Politeknik Negeri Pontianak Program Studi Hukum  site.co.id+1'],
            [2,'Universitas Tanjungpura Fakultas Kedokteran'],
            [2,'Universitas PGRI Pontianak - Jurusan Hukum'],
            [3,'RS Swasta Pratama Sehat Pontianak  Facebook+1'],
            [3,'Klinik Pratama Sehat Sentosa Pontianak'],
            [3,'RS Swasta Harapan Ibu Pontianak  Wikipedia'],
            [3,'Pusat Kesehatan Masyarakat (Puskesmas) Sehat Sentosa  Wikipedia'],
            [3,'Pusat Kesehatan Masyarakat (Puskesmas) Harapan Ibu  Wikipedia'],
            [3,'RS Swasta Medika Pontianak'],
            [3,'Pusat Kesehatan Masyarakat (Puskesmas) Medika'],
            [3,'Laboratorium Klinik Sehat Sentosa Pontianak'],
            [3,'RS Swasta Medika Pontianak'],
            [3,'Klinik Pratama Harapan Ibu Pontianak  site.co.id+1'],
            [3,'Klinik Pratama Dr. Soetomo Pontianak'],
            [3,'Laboratorium Klinik Sehat Sentosa Pontianak'],
            [3,'Laboratorium Klinik Dr. Soetomo Pontianak'],
            [3,'RSUD Kota Pontianak - Rumah Sakit Umum Daerah Medika'],
            [3,'Pusat Kesehatan Masyarakat (Puskesmas) Medika  Facebook+1'],
            [3,'RSUD Kota Pontianak - Rumah Sakit Umum Daerah Dr. Soetomo'],
            [3,'RS Swasta Pratama Sehat Pontianak'],
            [3,'RS Swasta Sehat Sentosa Pontianak  Facebook+1'],
            [3,'Laboratorium Klinik Harapan Ibu Pontianak'],
            [3,'RS Swasta Pratama Sehat Pontianak'],
            [3,'Klinik Pratama Medika Pontianak  site.co.id+1'],
            [3,'RSUD Kota Pontianak - Rumah Sakit Umum Daerah Medika'],
            [3,'Pusat Kesehatan Masyarakat (Puskesmas) Dr. Soetomo'],
            [3,'Laboratorium Klinik Medika Pontianak'],
            [3,'Laboratorium Klinik Pratama Sehat Pontianak'],
            [3,'RS Swasta Sehat Sentosa Pontianak'],
            [3,'Klinik Pratama Harapan Ibu Pontianak  Wikipedia'],
            [3,'Pusat Kesehatan Masyarakat (Puskesmas) Sehat Sentosa'],
            [3,'RSUD Kota Pontianak - Rumah Sakit Umum Daerah Pratama Sehat'],
            [3,'Laboratorium Klinik Pratama Sehat Pontianak'],
            [3,'RS Swasta Pratama Sehat Pontianak'],
            [3,'RSUD Kota Pontianak - Rumah Sakit Umum Daerah Harapan Ibu'],
            [3,'RSUD Kota Pontianak - Rumah Sakit Umum Daerah Pratama Sehat'],
            [3,'RSUD Kota Pontianak - Rumah Sakit Umum Daerah Sehat Sentosa'],
            [3,'Pusat Kesehatan Masyarakat (Puskesmas) Pratama Sehat'],
            [3,'RS Swasta Pratama Sehat Pontianak'],
            [3,'Laboratorium Klinik Harapan Ibu Pontianak'],
            [3,'Pusat Kesehatan Masyarakat (Puskesmas) Harapan Ibu'],
            [3,'RSUD Kota Pontianak - Rumah Sakit Umum Daerah Pratama Sehat'],
            [3,'Laboratorium Klinik Dr. Soetomo Pontianak'],
            [3,'Klinik Pratama Pratama Sehat Pontianak'],
            [3,'RSUD Kota Pontianak - Rumah Sakit Umum Daerah Sehat Sentosa'],
            [3,'RS Swasta Sehat Sentosa Pontianak'],
            [3,'RS Swasta Harapan Ibu Pontianak'],
            [3,'RS Swasta Pratama Sehat Pontianak  IDalamat.com+1'],
            [3,'RSUD Kota Pontianak - Rumah Sakit Umum Daerah Pratama Sehat  site.co.id+1'],
            [3,'RSUD Kota Pontianak - Rumah Sakit Umum Daerah Dr. Soetomo'],
            [3,'Pusat Kesehatan Masyarakat (Puskesmas) Dr. Soetomo'],
            [3,'Laboratorium Klinik Harapan Ibu Pontianak  Wikipedia'],
            [3,'Pusat Kesehatan Masyarakat (Puskesmas) Sehat Sentosa'],
            [3,'Pusat Kesehatan Masyarakat (Puskesmas) Sehat Sentosa'],
            [3,'Laboratorium Klinik Sehat Sentosa Pontianak'],
            [3,'Pusat Kesehatan Masyarakat (Puskesmas) Pratama Sehat'],
            [3,'RS Swasta Harapan Ibu Pontianak'],
            [3,'Pusat Kesehatan Masyarakat (Puskesmas) Dr. Soetomo'],
            [3,'Pusat Kesehatan Masyarakat (Puskesmas) Dr. Soetomo  Facebook+1'],
            [3,'RSUD Kota Pontianak - Rumah Sakit Umum Daerah Medika'],
            [3,'RSUD Kota Pontianak - Rumah Sakit Umum Daerah Pratama Sehat'],
            [3,'RS Swasta Pratama Sehat Pontianak  Wikipedia'],
            [3,'Klinik Pratama Dr. Soetomo Pontianak'],
            [3,'Pusat Kesehatan Masyarakat (Puskesmas) Dr. Soetomo'],
            [3,'Klinik Pratama Medika Pontianak  Facebook+1'],
            [3,'Pusat Kesehatan Masyarakat (Puskesmas) Medika'],
            [3,'RS Swasta Sehat Sentosa Pontianak'],
            [3,'RS Swasta Dr. Soetomo Pontianak'],
            [3,'Klinik Pratama Medika Pontianak'],
            [3,'Pusat Kesehatan Masyarakat (Puskesmas) Harapan Ibu'],
            [3,'Pusat Kesehatan Masyarakat (Puskesmas) Pratama Sehat'],
            [3,'Pusat Kesehatan Masyarakat (Puskesmas) Pratama Sehat'],
            [3,'RSUD Kota Pontianak - Rumah Sakit Umum Daerah Sehat Sentosa'],
            [3,'RS Swasta Sehat Sentosa Pontianak  site.co.id+1'],
            [3,'RS Swasta Dr. Soetomo Pontianak  Facebook+1'],
            [3,'Laboratorium Klinik Sehat Sentosa Pontianak  site.co.id+1'],
            [3,'Pusat Kesehatan Masyarakat (Puskesmas) Harapan Ibu'],
            [3,'RS Swasta Sehat Sentosa Pontianak'],
            [3,'Laboratorium Klinik Medika Pontianak  site.co.id+1'],
            [3,'Klinik Pratama Harapan Ibu Pontianak'],
            [3,'RSUD Kota Pontianak - Rumah Sakit Umum Daerah Dr. Soetomo'],
            [3,'Laboratorium Klinik Harapan Ibu Pontianak'],
            [3,'Pusat Kesehatan Masyarakat (Puskesmas) Dr. Soetomo'],
            [3,'Klinik Pratama Pratama Sehat Pontianak'],
            [3,'RS Swasta Harapan Ibu Pontianak'],
            [3,'RS Swasta Dr. Soetomo Pontianak  Instagram+1'],
            [3,'Pusat Kesehatan Masyarakat (Puskesmas) Dr. Soetomo'],
            [3,'Laboratorium Klinik Pratama Sehat Pontianak'],
            [3,'RSUD Kota Pontianak - Rumah Sakit Umum Daerah Pratama Sehat'],
            [3,'Laboratorium Klinik Medika Pontianak'],
            [3,'Klinik Pratama Harapan Ibu Pontianak  IDalamat.com+1'],
            [3,'Klinik Pratama Sehat Sentosa Pontianak'],
            [3,'Klinik Pratama Medika Pontianak'],
            [3,'Klinik Pratama Medika Pontianak'],
            [3,'Klinik Pratama Dr. Soetomo Pontianak'],
            [3,'RS Swasta Dr. Soetomo Pontianak'],
            [3,'Pusat Kesehatan Masyarakat (Puskesmas) Sehat Sentosa'],
            [3,'RS Swasta Sehat Sentosa Pontianak  site.co.id+1'],
            [3,'Laboratorium Klinik Medika Pontianak'],
            [3,'Laboratorium Klinik Sehat Sentosa Pontianak'],
            [3,'RS Swasta Dr. Soetomo Pontianak'],
            [3,'Pusat Kesehatan Masyarakat (Puskesmas) Sehat Sentosa'],
            [3,'RSUD Kota Pontianak - Rumah Sakit Umum Daerah Sehat Sentosa'],
            [3,'RS Swasta Medika Pontianak'],
            [3,'RSUD Kota Pontianak - Rumah Sakit Umum Daerah Pratama Sehat'],
            [3,'Klinik Pratama Sehat Sentosa Pontianak  IDalamat.com+1'],
            [3,'Klinik Pratama Medika Pontianak'],
            [3,'Klinik Pratama Harapan Ibu Pontianak  Wikipedia'],
            [3,'Pusat Kesehatan Masyarakat (Puskesmas) Medika'],
            [3,'Klinik Pratama Harapan Ibu Pontianak'],
            [3,'Laboratorium Klinik Medika Pontianak'],
            [3,'Pusat Kesehatan Masyarakat (Puskesmas) Sehat Sentosa'],
            [3,'Pusat Kesehatan Masyarakat (Puskesmas) Dr. Soetomo'],
            [3,'Laboratorium Klinik Pratama Sehat Pontianak'],
            [4,'Telkom Witel Kalimantan Barat - GraPARI Timur'],
            [4,'Pos Indonesia - Kantor Pos Barat Pontianak'],
            [4,'PDAM Tirta Khatulistiwa - Cabang Timur'],
            [4,'Pos Indonesia - Kantor Pos Timur Pontianak'],
            [4,'BPJS Kesehatan KC Pontianak - Kantor Pusat'],
            [4,'PLN UP3 Pontianak - Unit Selatan'],
            [4,'PDAM Tirta Khatulistiwa - Cabang Utara  site.co.id+1'],
            [4,'Telkom Witel Kalimantan Barat - GraPARI Selatan'],
            [4,'PDAM Tirta Khatulistiwa - Cabang Utara'],
            [4,'Pos Indonesia - Kantor Pos Selatan Pontianak'],
            [4,'PLN UP3 Pontianak - Unit Pusat  Wikipedia'],
            [4,'Pos Indonesia - Kantor Pos Timur Pontianak'],
            [4,'PDAM Tirta Khatulistiwa - Cabang Utara  site.co.id+1'],
            [4,'BPJS Kesehatan KC Pontianak - Kantor Utara  Facebook+1'],
            [4,'Pos Indonesia - Kantor Pos Selatan Pontianak'],
            [4,'Telkom Witel Kalimantan Barat - GraPARI Barat'],
            [4,'Pos Indonesia - Kantor Pos Timur Pontianak  Instagram+1'],
            [4,'Telkom Witel Kalimantan Barat - GraPARI Utara'],
            [4,'Telkom Witel Kalimantan Barat - GraPARI Selatan'],
            [4,'Pos Indonesia - Kantor Pos Pusat Pontianak'],
            [4,'BPJS Kesehatan KC Pontianak - Kantor Pusat'],
            [4,'BPJS Kesehatan KC Pontianak - Kantor Barat'],
            [4,'BPJS Kesehatan KC Pontianak - Kantor Selatan'],
            [4,'Telkom Witel Kalimantan Barat - GraPARI Selatan'],
            [4,'PDAM Tirta Khatulistiwa - Cabang Selatan'],
            [4,'PDAM Tirta Khatulistiwa - Cabang Pusat'],
            [4,'PLN UP3 Pontianak - Unit Selatan  site.co.id+1'],
            [4,'PDAM Tirta Khatulistiwa - Cabang Utara'],
            [4,'Pos Indonesia - Kantor Pos Barat Pontianak'],
            [4,'PDAM Tirta Khatulistiwa - Cabang Selatan  Wikipedia'],
            [4,'PLN UP3 Pontianak - Unit Pusat'],
            [4,'Pos Indonesia - Kantor Pos Timur Pontianak  Facebook+1'],
            [4,'BPJS Kesehatan KC Pontianak - Kantor Pusat  Facebook+1'],
            [4,'Pos Indonesia - Kantor Pos Timur Pontianak  Wikipedia'],
            [4,'BPJS Kesehatan KC Pontianak - Kantor Utara  Instagram+1'],
            [4,'PLN UP3 Pontianak - Unit Selatan  IDalamat.com+1'],
            [4,'Telkom Witel Kalimantan Barat - GraPARI Timur'],
            [4,'PLN UP3 Pontianak - Unit Utara  Instagram+1'],
            [4,'PDAM Tirta Khatulistiwa - Cabang Utara'],
            [4,'Telkom Witel Kalimantan Barat - GraPARI Selatan'],
            [4,'Pos Indonesia - Kantor Pos Barat Pontianak  Instagram+1'],
            [4,'PDAM Tirta Khatulistiwa - Cabang Utara'],
            [4,'PDAM Tirta Khatulistiwa - Cabang Pusat'],
            [4,'PLN UP3 Pontianak - Unit Barat  Instagram+1'],
            [4,'Telkom Witel Kalimantan Barat - GraPARI Pusat'],
            [4,'Pos Indonesia - Kantor Pos Pusat Pontianak  Wikipedia'],
            [4,'BPJS Kesehatan KC Pontianak - Kantor Timur'],
            [4,'Telkom Witel Kalimantan Barat - GraPARI Pusat'],
            [4,'BPJS Kesehatan KC Pontianak - Kantor Pusat  IDalamat.com+1'],
            [4,'Pos Indonesia - Kantor Pos Utara Pontianak'],
            [4,'BPJS Kesehatan KC Pontianak - Kantor Barat'],
            [4,'PLN UP3 Pontianak - Unit Pusat'],
            [4,'PDAM Tirta Khatulistiwa - Cabang Barat  Instagram+1'],
            [4,'Telkom Witel Kalimantan Barat - GraPARI Selatan'],
            [4,'Telkom Witel Kalimantan Barat - GraPARI Utara'],
            [4,'PLN UP3 Pontianak - Unit Selatan'],
            [4,'Telkom Witel Kalimantan Barat - GraPARI Barat'],
            [4,'Telkom Witel Kalimantan Barat - GraPARI Pusat  Facebook+1'],
            [4,'PLN UP3 Pontianak - Unit Utara  site.co.id+1'],
            [4,'PLN UP3 Pontianak - Unit Pusat'],
            [4,'BPJS Kesehatan KC Pontianak - Kantor Timur'],
            [4,'Pos Indonesia - Kantor Pos Utara Pontianak'],
            [4,'PDAM Tirta Khatulistiwa - Cabang Barat'],
            [4,'PDAM Tirta Khatulistiwa - Cabang Pusat'],
            [4,'PDAM Tirta Khatulistiwa - Cabang Timur'],
            [4,'PLN UP3 Pontianak - Unit Barat  Facebook+1'],
            [4,'Pos Indonesia - Kantor Pos Pusat Pontianak'],
            [4,'Telkom Witel Kalimantan Barat - GraPARI Pusat  IDalamat.com+1'],
            [4,'PLN UP3 Pontianak - Unit Barat'],
            [4,'PLN UP3 Pontianak - Unit Timur'],
            [4,'PDAM Tirta Khatulistiwa - Cabang Utara  Facebook+1'],
            [4,'BPJS Kesehatan KC Pontianak - Kantor Pusat  site.co.id+1'],
            [4,'PDAM Tirta Khatulistiwa - Cabang Timur'],
            [4,'PDAM Tirta Khatulistiwa - Cabang Selatan'],
            [4,'BPJS Kesehatan KC Pontianak - Kantor Barat'],
            [4,'PDAM Tirta Khatulistiwa - Cabang Selatan'],
            [4,'Telkom Witel Kalimantan Barat - GraPARI Barat'],
            [4,'BPJS Kesehatan KC Pontianak - Kantor Utara'],
            [4,'Pos Indonesia - Kantor Pos Timur Pontianak'],
            [4,'Telkom Witel Kalimantan Barat - GraPARI Selatan'],
            [4,'BPJS Kesehatan KC Pontianak - Kantor Utara'],
            [4,'PDAM Tirta Khatulistiwa - Cabang Timur'],
            [4,'BPJS Kesehatan KC Pontianak - Kantor Pusat'],
            [4,'Pos Indonesia - Kantor Pos Pusat Pontianak'],
            [4,'Pos Indonesia - Kantor Pos Selatan Pontianak'],
            [4,'Telkom Witel Kalimantan Barat - GraPARI Selatan'],
            [4,'Pos Indonesia - Kantor Pos Utara Pontianak'],
            [4,'PDAM Tirta Khatulistiwa - Cabang Selatan'],
            [4,'PDAM Tirta Khatulistiwa - Cabang Pusat'],
            [4,'Telkom Witel Kalimantan Barat - GraPARI Pusat  site.co.id+1'],
            [4,'Pos Indonesia - Kantor Pos Timur Pontianak'],
            [4,'Pos Indonesia - Kantor Pos Utara Pontianak'],
            [4,'Pos Indonesia - Kantor Pos Utara Pontianak  Facebook+1'],
            [4,'PDAM Tirta Khatulistiwa - Cabang Barat'],
            [4,'PLN UP3 Pontianak - Unit Utara'],
            [4,'BPJS Kesehatan KC Pontianak - Kantor Timur'],
            [4,'PDAM Tirta Khatulistiwa - Cabang Barat  site.co.id+1'],
            [4,'PLN UP3 Pontianak - Unit Barat'],
            [4,'BPJS Kesehatan KC Pontianak - Kantor Selatan'],
            [4,'PLN UP3 Pontianak - Unit Timur'],
            [4,'BPJS Kesehatan KC Pontianak - Kantor Timur'],
            [4,'Pos Indonesia - Kantor Pos Utara Pontianak'],
            [4,'BPJS Kesehatan KC Pontianak - Kantor Timur'],
            [4,'PDAM Tirta Khatulistiwa - Cabang Timur'],
            [4,'BPJS Kesehatan KC Pontianak - Kantor Pusat  Facebook+1'],
            [4,'Pos Indonesia - Kantor Pos Timur Pontianak'],
            [4,'BPJS Kesehatan KC Pontianak - Kantor Selatan'],
            [4,'PDAM Tirta Khatulistiwa - Cabang Utara'],
            [4,'Telkom Witel Kalimantan Barat - GraPARI Selatan'],
            [4,'PLN UP3 Pontianak - Unit Pusat'],
            [4,'PLN UP3 Pontianak - Unit Selatan'],
            [5,'BRI Kantor Cabang Pontianak - Unit No.3'],
            [5,'Bank Kalbar KCU Pontianak - Cabang No.5  site.co.id+1'],
            [5,'BCA KCU Pontianak - Cabang No.37'],
            [5,'BCA KCU Pontianak - Cabang No.6'],
            [5,'BTN Pontianak - Cabang No.17'],
            [5,'BTN Pontianak - Cabang No.14'],
            [5,'BCA KCU Pontianak - Cabang No.14  Wikipedia'],
            [5,'BRI Kantor Cabang Pontianak - Unit No.38  Instagram+1'],
            [5,'BCA KCU Pontianak - Cabang No.41  site.co.id+1'],
            [5,'BRI Kantor Cabang Pontianak - Unit No.14'],
            [5,'Bank Kalbar KCU Pontianak - Cabang No.33'],
            [5,'BTN Pontianak - Cabang No.6'],
            [5,'BCA KCU Pontianak - Cabang No.17'],
            [5,'BRI Kantor Cabang Pontianak - Unit No.33  Wikipedia'],
            [5,'BNI KCU Pontianak - Cabang No.10'],
            [5,'BNI KCU Pontianak - Cabang No.19'],
            [5,'BNI KCU Pontianak - Cabang No.23  IDalamat.com+1'],
            [5,'BCA KCU Pontianak - Cabang No.48'],
            [5,'BRI Kantor Cabang Pontianak - Unit No.30'],
            [5,'BRI Kantor Cabang Pontianak - Unit No.8'],
            [5,'BCA KCU Pontianak - Cabang No.21'],
            [5,'Bank Kalbar KCU Pontianak - Cabang No.21'],
            [5,'BRI Kantor Cabang Pontianak - Unit No.23  Wikipedia'],
            [5,'BTN Pontianak - Cabang No.22'],
            [5,'BCA KCU Pontianak - Cabang No.11'],
            [5,'BCA KCU Pontianak - Cabang No.48'],
            [5,'BNI KCU Pontianak - Cabang No.14'],
            [5,'BTN Pontianak - Cabang No.12  site.co.id+1'],
            [5,'BTN Pontianak - Cabang No.39  IDalamat.com+1'],
            [5,'BTN Pontianak - Cabang No.17'],
            [5,'Bank Kalbar KCU Pontianak - Cabang No.12'],
            [5,'BNI KCU Pontianak - Cabang No.24'],
            [5,'Bank Kalbar KCU Pontianak - Cabang No.47'],
            [5,'BCA KCU Pontianak - Cabang No.48'],
            [5,'BNI KCU Pontianak - Cabang No.30'],
            [5,'BRI Kantor Cabang Pontianak - Unit No.45  site.co.id+1'],
            [5,'BRI Kantor Cabang Pontianak - Unit No.7'],
            [5,'BTN Pontianak - Cabang No.34  Facebook+1'],
            [5,'BCA KCU Pontianak - Cabang No.40'],
            [5,'BCA KCU Pontianak - Cabang No.47'],
            [5,'BRI Kantor Cabang Pontianak - Unit No.1  Instagram+1'],
            [5,'BNI KCU Pontianak - Cabang No.38  IDalamat.com+1'],
            [5,'BRI Kantor Cabang Pontianak - Unit No.44'],
            [5,'Bank Kalbar KCU Pontianak - Cabang No.41'],
            [5,'Bank Kalbar KCU Pontianak - Cabang No.12'],
            [5,'BCA KCU Pontianak - Cabang No.49'],
            [5,'Bank Kalbar KCU Pontianak - Cabang No.15'],
            [5,'BCA KCU Pontianak - Cabang No.11'],
            [5,'BTN Pontianak - Cabang No.37  site.co.id+1'],
            [5,'BRI Kantor Cabang Pontianak - Unit No.18'],
            [5,'BCA KCU Pontianak - Cabang No.44'],
            [5,'BRI Kantor Cabang Pontianak - Unit No.33'],
            [5,'BNI KCU Pontianak - Cabang No.12'],
            [5,'BRI Kantor Cabang Pontianak - Unit No.13'],
            [5,'BRI Kantor Cabang Pontianak - Unit No.37  Instagram+1'],
            [5,'BCA KCU Pontianak - Cabang No.38'],
            [5,'Bank Kalbar KCU Pontianak - Cabang No.17  IDalamat.com+1'],
            [5,'BTN Pontianak - Cabang No.11'],
            [5,'BRI Kantor Cabang Pontianak - Unit No.17'],
            [5,'BTN Pontianak - Cabang No.41'],
            [5,'BTN Pontianak - Cabang No.18  Facebook+1'],
            [5,'BTN Pontianak - Cabang No.24  Facebook+1'],
            [5,'BRI Kantor Cabang Pontianak - Unit No.31'],
            [5,'BNI KCU Pontianak - Cabang No.46'],
            [5,'BTN Pontianak - Cabang No.36'],
            [5,'BNI KCU Pontianak - Cabang No.22'],
            [5,'BTN Pontianak - Cabang No.48'],
            [5,'BCA KCU Pontianak - Cabang No.11  Facebook+1'],
            [5,'BTN Pontianak - Cabang No.15  Wikipedia'],
            [5,'BNI KCU Pontianak - Cabang No.4'],
            [5,'BNI KCU Pontianak - Cabang No.19'],
            [5,'BNI KCU Pontianak - Cabang No.24'],
            [5,'BCA KCU Pontianak - Cabang No.50'],
            [5,'BCA KCU Pontianak - Cabang No.41  IDalamat.com+1'],
            [5,'BNI KCU Pontianak - Cabang No.48'],
            [5,'BRI Kantor Cabang Pontianak - Unit No.40  Instagram+1'],
            [5,'BTN Pontianak - Cabang No.42'],
            [5,'BRI Kantor Cabang Pontianak - Unit No.36'],
            [5,'BRI Kantor Cabang Pontianak - Unit No.4  site.co.id+1'],
            [5,'Bank Kalbar KCU Pontianak - Cabang No.35'],
            [5,'BNI KCU Pontianak - Cabang No.26  Wikipedia'],
            [5,'BTN Pontianak - Cabang No.22'],
            [5,'Bank Kalbar KCU Pontianak - Cabang No.2'],
            [5,'BRI Kantor Cabang Pontianak - Unit No.13  Wikipedia'],
            [5,'Bank Kalbar KCU Pontianak - Cabang No.25'],
            [5,'Bank Kalbar KCU Pontianak - Cabang No.27'],
            [5,'BNI KCU Pontianak - Cabang No.13  Instagram+1'],
            [5,'Bank Kalbar KCU Pontianak - Cabang No.28'],
            [5,'BRI Kantor Cabang Pontianak - Unit No.35'],
            [5,'BCA KCU Pontianak - Cabang No.31'],
            [5,'Bank Kalbar KCU Pontianak - Cabang No.18'],
            [5,'Bank Kalbar KCU Pontianak - Cabang No.47'],
            [5,'BTN Pontianak - Cabang No.48'],
            [5,'BNI KCU Pontianak - Cabang No.3'],
            [5,'BCA KCU Pontianak - Cabang No.37  site.co.id+1'],
            [5,'Bank Kalbar KCU Pontianak - Cabang No.13'],
            [5,'BNI KCU Pontianak - Cabang No.44'],
            [5,'BNI KCU Pontianak - Cabang No.40'],
            [5,'BRI Kantor Cabang Pontianak - Unit No.23  Wikipedia'],
            [5,'BRI Kantor Cabang Pontianak - Unit No.34'],
            [5,'BNI KCU Pontianak - Cabang No.29  site.co.id+1'],
            [5,'BRI Kantor Cabang Pontianak - Unit No.28'],
            [5,'BRI Kantor Cabang Pontianak - Unit No.29  Facebook+1'],
            [5,'BCA KCU Pontianak - Cabang No.2'],
            [5,'BTN Pontianak - Cabang No.3'],
            [5,'BRI Kantor Cabang Pontianak - Unit No.39'],
            [5,'BCA KCU Pontianak - Cabang No.23'],
            [5,'BNI KCU Pontianak - Cabang No.43'],
            [5,'BTN Pontianak - Cabang No.40'],
            [5,'BCA KCU Pontianak - Cabang No.38'],
            [5,'BCA KCU Pontianak - Cabang No.41'],
            [6,'J&T Express - Drop Point D-15 Pontianak'],
            [6,'JNE Kantor Cabang Pontianak - Cabang B-20'],
            [6,'Perum DAMRI - Pool C-13 Pontianak'],
            [6,'J&T Express - Drop Point C-10 Pontianak'],
            [6,'Pelabuhan Pontianak - Dermaga A-17'],
            [6,'JNE Kantor Cabang Pontianak - Cabang D-20'],
            [6,'JNE Kantor Cabang Pontianak - Cabang A-9'],
            [6,'JNE Kantor Cabang Pontianak - Cabang B-12'],
            [6,'Perum DAMRI - Pool A-7 Pontianak  Wikipedia'],
            [6,'J&T Express - Drop Point D-8 Pontianak'],
            [6,'Perum DAMRI - Pool A-3 Pontianak'],
            [6,'Bandara Internasional Supadio - Terminal B-8'],
            [6,'J&T Express - Drop Point A-13 Pontianak'],
            [6,'Pelabuhan Pontianak - Dermaga A-16  Instagram+1'],
            [6,'Perum DAMRI - Pool D-10 Pontianak'],
            [6,'JNE Kantor Cabang Pontianak - Cabang B-16'],
            [6,'Bandara Internasional Supadio - Terminal C-12'],
            [6,'Bandara Internasional Supadio - Terminal A-8'],
            [6,'Perum DAMRI - Pool C-17 Pontianak'],
            [6,'Perum DAMRI - Pool A-6 Pontianak'],
            [6,'Pelabuhan Pontianak - Dermaga A-5'],
            [6,'J&T Express - Drop Point C-18 Pontianak'],
            [6,'J&T Express - Drop Point A-4 Pontianak  IDalamat.com+1'],
            [6,'Bandara Internasional Supadio - Terminal D-4  site.co.id+1'],
            [6,'Perum DAMRI - Pool A-1 Pontianak'],
            [6,'Bandara Internasional Supadio - Terminal B-5'],
            [6,'Perum DAMRI - Pool A-5 Pontianak'],
            [6,'JNE Kantor Cabang Pontianak - Cabang D-1'],
            [6,'Perum DAMRI - Pool B-9 Pontianak  IDalamat.com+1'],
            [6,'Pelabuhan Pontianak - Dermaga A-4  IDalamat.com+1'],
            [6,'J&T Express - Drop Point D-6 Pontianak'],
            [6,'Perum DAMRI - Pool D-8 Pontianak'],
            [6,'Pelabuhan Pontianak - Dermaga B-10'],
            [6,'J&T Express - Drop Point B-13 Pontianak  site.co.id+1'],
            [6,'J&T Express - Drop Point B-20 Pontianak'],
            [6,'JNE Kantor Cabang Pontianak - Cabang D-4'],
            [6,'JNE Kantor Cabang Pontianak - Cabang C-2'],
            [6,'J&T Express - Drop Point D-6 Pontianak'],
            [6,'Perum DAMRI - Pool B-10 Pontianak'],
            [6,'JNE Kantor Cabang Pontianak - Cabang B-20'],
            [6,'Pelabuhan Pontianak - Dermaga D-7'],
            [6,'Bandara Internasional Supadio - Terminal A-16'],
            [6,'Perum DAMRI - Pool C-17 Pontianak'],
            [6,'Bandara Internasional Supadio - Terminal B-12'],
            [6,'Perum DAMRI - Pool B-8 Pontianak'],
            [6,'JNE Kantor Cabang Pontianak - Cabang C-13'],
            [6,'Pelabuhan Pontianak - Dermaga C-6  Instagram+1'],
            [6,'Bandara Internasional Supadio - Terminal C-11'],
            [6,'Bandara Internasional Supadio - Terminal B-3'],
            [6,'Pelabuhan Pontianak - Dermaga D-16'],
            [6,'Pelabuhan Pontianak - Dermaga D-2'],
            [6,'J&T Express - Drop Point C-3 Pontianak  Instagram+1'],
            [6,'J&T Express - Drop Point D-14 Pontianak'],
            [6,'Perum DAMRI - Pool C-5 Pontianak  Instagram+1'],
            [6,'Pelabuhan Pontianak - Dermaga C-17'],
            [6,'Bandara Internasional Supadio - Terminal A-2'],
            [6,'Perum DAMRI - Pool B-6 Pontianak  Facebook+1'],
            [6,'J&T Express - Drop Point C-16 Pontianak'],
            [6,'JNE Kantor Cabang Pontianak - Cabang C-9'],
            [6,'Bandara Internasional Supadio - Terminal A-4'],
            [6,'J&T Express - Drop Point D-11 Pontianak  Wikipedia'],
            [6,'Pelabuhan Pontianak - Dermaga A-3'],
            [6,'Bandara Internasional Supadio - Terminal D-16'],
            [6,'Perum DAMRI - Pool C-12 Pontianak'],
            [6,'Pelabuhan Pontianak - Dermaga D-17  Instagram+1'],
            [6,'Bandara Internasional Supadio - Terminal D-18'],
            [6,'Pelabuhan Pontianak - Dermaga C-6'],
            [6,'JNE Kantor Cabang Pontianak - Cabang D-11'],
            [6,'JNE Kantor Cabang Pontianak - Cabang D-18'],
            [6,'J&T Express - Drop Point D-2 Pontianak'],
            [6,'Bandara Internasional Supadio - Terminal B-4'],
            [6,'J&T Express - Drop Point C-13 Pontianak'],
            [6,'JNE Kantor Cabang Pontianak - Cabang A-20'],
            [6,'Perum DAMRI - Pool A-18 Pontianak  site.co.id+1'],
            [6,'J&T Express - Drop Point B-10 Pontianak'],
            [6,'Bandara Internasional Supadio - Terminal C-19'],
            [6,'Bandara Internasional Supadio - Terminal A-16  Wikipedia'],
            [6,'Perum DAMRI - Pool D-8 Pontianak  IDalamat.com+1'],
            [6,'Pelabuhan Pontianak - Dermaga B-19'],
            [6,'JNE Kantor Cabang Pontianak - Cabang D-7'],
            [6,'Perum DAMRI - Pool C-13 Pontianak'],
            [6,'Perum DAMRI - Pool D-5 Pontianak  Facebook+1'],
            [6,'Perum DAMRI - Pool B-8 Pontianak'],
            [6,'Pelabuhan Pontianak - Dermaga B-1'],
            [6,'Perum DAMRI - Pool C-6 Pontianak'],
            [6,'Pelabuhan Pontianak - Dermaga C-6  Wikipedia'],
            [6,'Pelabuhan Pontianak - Dermaga A-1  site.co.id+1'],
            [6,'Pelabuhan Pontianak - Dermaga A-20'],
            [6,'Perum DAMRI - Pool B-11 Pontianak'],
            [6,'J&T Express - Drop Point A-10 Pontianak  Facebook+1'],
            [6,'Perum DAMRI - Pool A-7 Pontianak  site.co.id+1'],
            [6,'Pelabuhan Pontianak - Dermaga C-1'],
            [6,'Perum DAMRI - Pool A-14 Pontianak'],
            [6,'Pelabuhan Pontianak - Dermaga C-16  Instagram+1'],
            [6,'JNE Kantor Cabang Pontianak - Cabang A-2'],
            [6,'JNE Kantor Cabang Pontianak - Cabang D-10'],
            [6,'J&T Express - Drop Point C-11 Pontianak'],
            [6,'Bandara Internasional Supadio - Terminal D-1'],
            [6,'Bandara Internasional Supadio - Terminal C-20  site.co.id+1'],
            [6,'JNE Kantor Cabang Pontianak - Cabang D-2'],
            [6,'JNE Kantor Cabang Pontianak - Cabang A-12'],
            [6,'Pelabuhan Pontianak - Dermaga D-6  IDalamat.com+1'],
            [6,'J&T Express - Drop Point A-8 Pontianak'],
            [6,'Perum DAMRI - Pool A-3 Pontianak'],
            [6,'JNE Kantor Cabang Pontianak - Cabang C-2'],
            [6,'J&T Express - Drop Point B-1 Pontianak  Facebook+1'],
            [6,'J&T Express - Drop Point B-17 Pontianak'],
            [6,'J&T Express - Drop Point A-19 Pontianak  IDalamat.com+1'],
            [6,'Bandara Internasional Supadio - Terminal B-10'],
            [6,'Pelabuhan Pontianak - Dermaga B-11'],
            [6,'Pelabuhan Pontianak - Dermaga C-19'],
            [7,'Mitra Anda Department Store - Outlet Unit 23'],
            [7,'Ayani Megamal - Tenant Unit 76  Wikipedia'],
            [7,'Mitra Anda Department Store - Outlet Unit 7'],
            [7,'Gramedia Pontianak - Gerai Unit 113'],
            [7,'Gramedia Pontianak - Gerai Unit 42'],
            [7,'Ramayana Pontianak - Toko Unit 91'],
            [7,'Ramayana Pontianak - Toko Unit 82'],
            [7,'Ramayana Pontianak - Toko Unit 34  Wikipedia'],
            [7,'Ayani Megamal - Tenant Unit 16'],
            [7,'Ramayana Pontianak - Toko Unit 3'],
            [7,'Mitra Anda Department Store - Outlet Unit 72  Wikipedia'],
            [7,'Gramedia Pontianak - Gerai Unit 110'],
            [7,'Mitra Anda Department Store - Outlet Unit 61'],
            [7,'Ramayana Pontianak - Toko Unit 15  IDalamat.com+1'],
            [7,'GAIA Bumi Raya City - Tenant Unit 15'],
            [7,'Ramayana Pontianak - Toko Unit 68'],
            [7,'GAIA Bumi Raya City - Tenant Unit 39'],
            [7,'Gramedia Pontianak - Gerai Unit 87  Facebook+1'],
            [7,'GAIA Bumi Raya City - Tenant Unit 96'],
            [7,'Mitra Anda Department Store - Outlet Unit 21'],
            [7,'Ramayana Pontianak - Toko Unit 29'],
            [7,'Mitra Anda Department Store - Outlet Unit 88'],
            [7,'Ayani Megamal - Tenant Unit 108'],
            [7,'GAIA Bumi Raya City - Tenant Unit 3'],
            [7,'Ayani Megamal - Tenant Unit 70'],
            [7,'GAIA Bumi Raya City - Tenant Unit 110  Facebook+1'],
            [7,'Gramedia Pontianak - Gerai Unit 14'],
            [7,'Gramedia Pontianak - Gerai Unit 59'],
            [7,'Mitra Anda Department Store - Outlet Unit 77'],
            [7,'Ramayana Pontianak - Toko Unit 59'],
            [7,'Ayani Megamal - Tenant Unit 87'],
            [7,'Mitra Anda Department Store - Outlet Unit 77  Instagram+1'],
            [7,'Ayani Megamal - Tenant Unit 119'],
            [7,'GAIA Bumi Raya City - Tenant Unit 42'],
            [7,'GAIA Bumi Raya City - Tenant Unit 20'],
            [7,'GAIA Bumi Raya City - Tenant Unit 33'],
            [7,'Ramayana Pontianak - Toko Unit 23'],
            [7,'Mitra Anda Department Store - Outlet Unit 72  site.co.id+1'],
            [7,'Mitra Anda Department Store - Outlet Unit 35'],
            [7,'Ramayana Pontianak - Toko Unit 6  site.co.id+1'],
            [7,'Gramedia Pontianak - Gerai Unit 58'],
            [7,'Ayani Megamal - Tenant Unit 39'],
            [7,'Gramedia Pontianak - Gerai Unit 79  IDalamat.com+1'],
            [7,'Ayani Megamal - Tenant Unit 38'],
            [7,'Gramedia Pontianak - Gerai Unit 29  Instagram+1'],
            [7,'Ayani Megamal - Tenant Unit 113'],
            [7,'Ramayana Pontianak - Toko Unit 92  site.co.id+1'],
            [7,'Ramayana Pontianak - Toko Unit 74'],
            [7,'Ayani Megamal - Tenant Unit 75'],
            [7,'GAIA Bumi Raya City - Tenant Unit 3'],
            [7,'Mitra Anda Department Store - Outlet Unit 16  IDalamat.com+1'],
            [7,'Ramayana Pontianak - Toko Unit 112'],
            [7,'GAIA Bumi Raya City - Tenant Unit 73'],
            [7,'Ramayana Pontianak - Toko Unit 32  site.co.id+1'],
            [7,'Ramayana Pontianak - Toko Unit 55'],
            [7,'Gramedia Pontianak - Gerai Unit 102'],
            [7,'Mitra Anda Department Store - Outlet Unit 3  Instagram+1'],
            [7,'Mitra Anda Department Store - Outlet Unit 3  Wikipedia'],
            [7,'Ayani Megamal - Tenant Unit 94'],
            [7,'Ramayana Pontianak - Toko Unit 113'],
            [7,'Mitra Anda Department Store - Outlet Unit 96'],
            [7,'Gramedia Pontianak - Gerai Unit 115'],
            [7,'Ramayana Pontianak - Toko Unit 6'],
            [7,'Gramedia Pontianak - Gerai Unit 59'],
            [7,'Ayani Megamal - Tenant Unit 5'],
            [7,'Ramayana Pontianak - Toko Unit 56'],
            [7,'Ramayana Pontianak - Toko Unit 105'],
            [7,'Ramayana Pontianak - Toko Unit 86'],
            [7,'Ayani Megamal - Tenant Unit 11'],
            [7,'Gramedia Pontianak - Gerai Unit 23'],
            [7,'Mitra Anda Department Store - Outlet Unit 104  Instagram+1'],
            [7,'Ramayana Pontianak - Toko Unit 7'],
            [7,'Ramayana Pontianak - Toko Unit 76  Wikipedia'],
            [7,'Ramayana Pontianak - Toko Unit 88'],
            [7,'Gramedia Pontianak - Gerai Unit 98'],
            [7,'Ayani Megamal - Tenant Unit 69'],
            [7,'Mitra Anda Department Store - Outlet Unit 6'],
            [7,'Mitra Anda Department Store - Outlet Unit 3'],
            [7,'Ayani Megamal - Tenant Unit 107'],
            [7,'GAIA Bumi Raya City - Tenant Unit 94'],
            [7,'Gramedia Pontianak - Gerai Unit 72  site.co.id+1'],
            [7,'Ramayana Pontianak - Toko Unit 103'],
            [7,'Mitra Anda Department Store - Outlet Unit 33'],
            [7,'Ayani Megamal - Tenant Unit 91'],
            [7,'Ramayana Pontianak - Toko Unit 30'],
            [7,'GAIA Bumi Raya City - Tenant Unit 62'],
            [7,'Mitra Anda Department Store - Outlet Unit 91'],
            [7,'Ayani Megamal - Tenant Unit 17'],
            [7,'Ramayana Pontianak - Toko Unit 8  Instagram+1'],
            [7,'Gramedia Pontianak - Gerai Unit 79'],
            [7,'Ayani Megamal - Tenant Unit 40  Wikipedia'],
            [7,'Mitra Anda Department Store - Outlet Unit 113'],
            [7,'Gramedia Pontianak - Gerai Unit 81'],
            [7,'Gramedia Pontianak - Gerai Unit 7'],
            [7,'Gramedia Pontianak - Gerai Unit 9  Instagram+1'],
            [7,'Ramayana Pontianak - Toko Unit 113'],
            [7,'GAIA Bumi Raya City - Tenant Unit 102  site.co.id+1'],
            [7,'Ramayana Pontianak - Toko Unit 69'],
            [7,'Ramayana Pontianak - Toko Unit 113'],
            [7,'Ayani Megamal - Tenant Unit 82  Facebook+1'],
            [7,'Ayani Megamal - Tenant Unit 37'],
            [7,'Mitra Anda Department Store - Outlet Unit 41'],
            [7,'Ramayana Pontianak - Toko Unit 85'],
            [7,'Gramedia Pontianak - Gerai Unit 99'],
            [7,'Ramayana Pontianak - Toko Unit 45'],
            [7,'Mitra Anda Department Store - Outlet Unit 57'],
            [7,'Mitra Anda Department Store - Outlet Unit 1'],
            [7,'Ramayana Pontianak - Toko Unit 60'],
            [7,'Ayani Megamal - Tenant Unit 61  IDalamat.com+1'],
            [7,'Ayani Megamal - Tenant Unit 16'],
            [7,'Mitra Anda Department Store - Outlet Unit 43'],
            [8,'Ibis Transera 5 Pontianak'],
            [8,'Hotel Transera 5 Pontianak'],
            [8,'Resort Borneo 1 Kubu Raya'],
            [8,'Hotel Borneo 4 Pontianak  Facebook+1'],
            [8,'Resort Borneo 1 Kubu Raya  Facebook+1'],
            [8,'Hotel Orchardz 2 Pontianak'],
            [8,'Aston Orchardz 5 Pontianak'],
            [8,'Hotel Orchardz 2 Pontianak'],
            [8,'Aston Swiss-Belinn 1 Pontianak'],
            [8,'Ibis Neo Gajah Mada 1 Pontianak  Wikipedia'],
            [8,'Aston Orchardz 2 Pontianak  site.co.id+1'],
            [8,'Ibis Borneo 2 Pontianak'],
            [8,'Guest House Orchardz 3 Pontianak'],
            [8,'Aston Swiss-Belinn 1 Pontianak'],
            [8,'Hotel Swiss-Belinn 4 Pontianak'],
            [8,'Hotel Neo Gajah Mada 3 Pontianak'],
            [8,'Resort Neo Gajah Mada 4 Kubu Raya'],
            [8,'Ibis Swiss-Belinn 4 Pontianak'],
            [8,'Guest House Swiss-Belinn 3 Pontianak  Facebook+1'],
            [8,'Hotel Neo Gajah Mada 5 Pontianak'],
            [8,'Ibis Neo Gajah Mada 3 Pontianak'],
            [8,'Aston Borneo 1 Pontianak'],
            [8,'Hotel Neo Gajah Mada 4 Pontianak  Facebook+1'],
            [8,'Aston Swiss-Belinn 4 Pontianak'],
            [8,'Guest House Neo Gajah Mada 3 Pontianak'],
            [8,'Resort Neo Gajah Mada 1 Kubu Raya'],
            [8,'Hotel Swiss-Belinn 2 Pontianak'],
            [8,'Ibis Neo Gajah Mada 1 Pontianak'],
            [8,'Resort Orchardz 5 Kubu Raya  site.co.id+1'],
            [8,'Resort Borneo 3 Kubu Raya'],
            [8,'Aston Transera 4 Pontianak'],
            [8,'Guest House Transera 5 Pontianak  IDalamat.com+1'],
            [8,'Hotel Neo Gajah Mada 1 Pontianak'],
            [8,'Resort Swiss-Belinn 2 Kubu Raya'],
            [8,'Hotel Transera 4 Pontianak  Facebook+1'],
            [8,'Resort Borneo 5 Kubu Raya'],
            [8,'Aston Transera 4 Pontianak  Instagram+1'],
            [8,'Aston Swiss-Belinn 1 Pontianak'],
            [8,'Guest House Neo Gajah Mada 4 Pontianak'],
            [8,'Guest House Borneo 4 Pontianak'],
            [8,'Aston Neo Gajah Mada 2 Pontianak'],
            [8,'Hotel Swiss-Belinn 2 Pontianak'],
            [8,'Resort Neo Gajah Mada 1 Kubu Raya'],
            [8,'Aston Swiss-Belinn 2 Pontianak'],
            [8,'Aston Borneo 4 Pontianak'],
            [8,'Ibis Orchardz 2 Pontianak'],
            [8,'Ibis Neo Gajah Mada 3 Pontianak'],
            [8,'Hotel Borneo 1 Pontianak  IDalamat.com+1'],
            [8,'Resort Orchardz 1 Kubu Raya'],
            [8,'Ibis Swiss-Belinn 5 Pontianak  Facebook+1'],
            [8,'Hotel Neo Gajah Mada 3 Pontianak'],
            [8,'Aston Swiss-Belinn 1 Pontianak  Instagram+1'],
            [8,'Aston Swiss-Belinn 2 Pontianak'],
            [8,'Hotel Neo Gajah Mada 3 Pontianak  Instagram+1'],
            [8,'Ibis Swiss-Belinn 5 Pontianak  IDalamat.com+1'],
            [8,'Resort Swiss-Belinn 5 Kubu Raya'],
            [8,'Guest House Swiss-Belinn 3 Pontianak'],
            [8,'Ibis Neo Gajah Mada 5 Pontianak'],
            [8,'Ibis Borneo 1 Pontianak'],
            [8,'Ibis Transera 2 Pontianak'],
            [8,'Aston Transera 4 Pontianak'],
            [8,'Aston Orchardz 1 Pontianak'],
            [8,'Hotel Neo Gajah Mada 5 Pontianak'],
            [8,'Resort Neo Gajah Mada 4 Kubu Raya'],
            [8,'Resort Neo Gajah Mada 2 Kubu Raya'],
            [8,'Ibis Transera 1 Pontianak  Wikipedia'],
            [8,'Ibis Orchardz 3 Pontianak'],
            [8,'Resort Swiss-Belinn 2 Kubu Raya'],
            [8,'Hotel Borneo 1 Pontianak  site.co.id+1'],
            [8,'Resort Swiss-Belinn 5 Kubu Raya'],
            [8,'Resort Orchardz 3 Kubu Raya'],
            [8,'Guest House Borneo 2 Pontianak'],
            [8,'Guest House Transera 5 Pontianak  Facebook+1'],
            [8,'Hotel Borneo 1 Pontianak'],
            [8,'Ibis Swiss-Belinn 4 Pontianak'],
            [8,'Resort Transera 5 Kubu Raya'],
            [8,'Hotel Neo Gajah Mada 3 Pontianak'],
            [8,'Aston Neo Gajah Mada 1 Pontianak  site.co.id+1'],
            [8,'Resort Transera 3 Kubu Raya'],
            [8,'Hotel Swiss-Belinn 2 Pontianak'],
            [8,'Guest House Transera 2 Pontianak  Instagram+1'],
            [8,'Ibis Borneo 1 Pontianak  IDalamat.com+1'],
            [8,'Resort Swiss-Belinn 3 Kubu Raya'],
            [8,'Aston Swiss-Belinn 2 Pontianak'],
            [8,'Guest House Swiss-Belinn 5 Pontianak  Instagram+1'],
            [8,'Ibis Borneo 4 Pontianak'],
            [8,'Guest House Swiss-Belinn 1 Pontianak'],
            [8,'Aston Swiss-Belinn 1 Pontianak'],
            [8,'Guest House Transera 2 Pontianak'],
            [8,'Hotel Transera 3 Pontianak  IDalamat.com+1'],
            [8,'Guest House Transera 3 Pontianak'],
            [8,'Aston Orchardz 2 Pontianak'],
            [8,'Ibis Borneo 5 Pontianak'],
            [8,'Guest House Transera 4 Pontianak'],
            [8,'Guest House Orchardz 2 Pontianak'],
            [8,'Hotel Transera 1 Pontianak  Instagram+1'],
            [8,'Guest House Neo Gajah Mada 1 Pontianak'],
            [8,'Guest House Neo Gajah Mada 4 Pontianak  IDalamat.com+1'],
            [8,'Aston Transera 4 Pontianak'],
            [8,'Hotel Orchardz 3 Pontianak  site.co.id+1'],
            [8,'Aston Transera 1 Pontianak  site.co.id+1'],
            [8,'Ibis Borneo 4 Pontianak  site.co.id+1'],
            [8,'Hotel Orchardz 3 Pontianak'],
            [8,'Hotel Orchardz 4 Pontianak'],
            [8,'Guest House Neo Gajah Mada 2 Pontianak  IDalamat.com+1'],
            [8,'Hotel Borneo 3 Pontianak'],
            [8,'Resort Neo Gajah Mada 5 Kubu Raya'],
            [8,'Guest House Borneo 5 Pontianak'],
            [8,'Resort Neo Gajah Mada 1 Kubu Raya'],
            [8,'Hotel Orchardz 4 Pontianak'],
            [8,'Resort Orchardz 4 Kubu Raya'],
            [9,'Provider Internet Lokal Branch-4 Pontianak'],
            [9,'Indosat Ooredoo Hutchison - Branch Pontianak Branch-1'],
            [9,'XL Axiata - GraPARI Pontianak Branch-5'],
            [9,'Provider Internet Lokal Branch-3 Pontianak  Facebook+1'],
            [9,'Provider Internet Lokal Branch-2 Pontianak  IDalamat.com+1'],
            [9,'Warung Internet Branch-6 Pontianak  site.co.id+1'],
            [9,'Warung Internet Branch-2 Pontianak'],
            [9,'XL Axiata - GraPARI Pontianak Branch-10'],
            [9,'XL Axiata - GraPARI Pontianak Branch-3  site.co.id+1'],
            [9,'Indosat Ooredoo Hutchison - Branch Pontianak Branch-8'],
            [9,'Indosat Ooredoo Hutchison - Branch Pontianak Branch-7'],
            [9,'Indosat Ooredoo Hutchison - Branch Pontianak Branch-6'],
            [9,'Provider Internet Lokal Branch-5 Pontianak  Facebook+1'],
            [9,'Telkomsel GraPARI Pontianak - Cabang Branch-10'],
            [9,'Indosat Ooredoo Hutchison - Branch Pontianak Branch-8'],
            [9,'Telkomsel GraPARI Pontianak - Cabang Branch-9'],
            [9,'Indosat Ooredoo Hutchison - Branch Pontianak Branch-6'],
            [9,'Indosat Ooredoo Hutchison - Branch Pontianak Branch-9  Instagram+1'],
            [9,'XL Axiata - GraPARI Pontianak Branch-10'],
            [9,'XL Axiata - GraPARI Pontianak Branch-4'],
            [9,'Warung Internet Branch-1 Pontianak'],
            [9,'Indosat Ooredoo Hutchison - Branch Pontianak Branch-7'],
            [9,'Indosat Ooredoo Hutchison - Branch Pontianak Branch-6'],
            [9,'Provider Internet Lokal Branch-4 Pontianak'],
            [9,'XL Axiata - GraPARI Pontianak Branch-7'],
            [9,'Warung Internet Branch-4 Pontianak'],
            [9,'Provider Internet Lokal Branch-8 Pontianak'],
            [9,'Telkomsel GraPARI Pontianak - Cabang Branch-6'],
            [9,'Warung Internet Branch-6 Pontianak  Instagram+1'],
            [9,'Warung Internet Branch-7 Pontianak  Instagram+1'],
            [9,'Telkomsel GraPARI Pontianak - Cabang Branch-2'],
            [9,'Indosat Ooredoo Hutchison - Branch Pontianak Branch-3'],
            [9,'Indosat Ooredoo Hutchison - Branch Pontianak Branch-8  Wikipedia'],
            [9,'XL Axiata - GraPARI Pontianak Branch-3'],
            [9,'Warung Internet Branch-2 Pontianak'],
            [9,'Warung Internet Branch-1 Pontianak  Instagram+1'],
            [9,'Provider Internet Lokal Branch-1 Pontianak'],
            [9,'Indosat Ooredoo Hutchison - Branch Pontianak Branch-7  Instagram+1'],
            [9,'Indosat Ooredoo Hutchison - Branch Pontianak Branch-1'],
            [9,'Provider Internet Lokal Branch-6 Pontianak'],
            [9,'Provider Internet Lokal Branch-3 Pontianak'],
            [9,'Warung Internet Branch-9 Pontianak'],
            [9,'Warung Internet Branch-4 Pontianak'],
            [9,'Warung Internet Branch-10 Pontianak'],
            [9,'Warung Internet Branch-8 Pontianak  site.co.id+1'],
            [9,'Indosat Ooredoo Hutchison - Branch Pontianak Branch-7'],
            [9,'Indosat Ooredoo Hutchison - Branch Pontianak Branch-10'],
            [9,'XL Axiata - GraPARI Pontianak Branch-2'],
            [9,'Telkomsel GraPARI Pontianak - Cabang Branch-3'],
            [9,'Warung Internet Branch-6 Pontianak'],
            [9,'Indosat Ooredoo Hutchison - Branch Pontianak Branch-4'],
            [9,'Indosat Ooredoo Hutchison - Branch Pontianak Branch-4'],
            [9,'Warung Internet Branch-2 Pontianak  Instagram+1'],
            [9,'XL Axiata - GraPARI Pontianak Branch-6'],
            [9,'Provider Internet Lokal Branch-10 Pontianak'],
            [9,'Telkomsel GraPARI Pontianak - Cabang Branch-1'],
            [9,'Telkomsel GraPARI Pontianak - Cabang Branch-9'],
            [9,'Telkomsel GraPARI Pontianak - Cabang Branch-5  Wikipedia'],
            [9,'Warung Internet Branch-7 Pontianak'],
            [9,'Provider Internet Lokal Branch-5 Pontianak  site.co.id+1'],
            [9,'Provider Internet Lokal Branch-9 Pontianak'],
            [9,'XL Axiata - GraPARI Pontianak Branch-2'],
            [9,'Indosat Ooredoo Hutchison - Branch Pontianak Branch-10'],
            [9,'Telkomsel GraPARI Pontianak - Cabang Branch-6'],
            [9,'XL Axiata - GraPARI Pontianak Branch-8'],
            [9,'Provider Internet Lokal Branch-1 Pontianak'],
            [9,'XL Axiata - GraPARI Pontianak Branch-2'],
            [9,'Indosat Ooredoo Hutchison - Branch Pontianak Branch-6'],
            [9,'Indosat Ooredoo Hutchison - Branch Pontianak Branch-8'],
            [9,'Warung Internet Branch-7 Pontianak  Facebook+1'],
            [9,'Provider Internet Lokal Branch-7 Pontianak'],
            [9,'Indosat Ooredoo Hutchison - Branch Pontianak Branch-3'],
            [9,'Indosat Ooredoo Hutchison - Branch Pontianak Branch-7'],
            [9,'Telkomsel GraPARI Pontianak - Cabang Branch-10'],
            [9,'Provider Internet Lokal Branch-1 Pontianak  Facebook+1'],
            [9,'Indosat Ooredoo Hutchison - Branch Pontianak Branch-2'],
            [9,'Telkomsel GraPARI Pontianak - Cabang Branch-9  Instagram+1'],
            [9,'Telkomsel GraPARI Pontianak - Cabang Branch-7'],
            [9,'Indosat Ooredoo Hutchison - Branch Pontianak Branch-7'],
            [9,'Provider Internet Lokal Branch-6 Pontianak'],
            [9,'XL Axiata - GraPARI Pontianak Branch-1  site.co.id+1'],
            [9,'Indosat Ooredoo Hutchison - Branch Pontianak Branch-7'],
            [9,'Indosat Ooredoo Hutchison - Branch Pontianak Branch-6'],
            [9,'Warung Internet Branch-7 Pontianak'],
            [9,'Warung Internet Branch-9 Pontianak'],
            [9,'Provider Internet Lokal Branch-9 Pontianak'],
            [9,'Indosat Ooredoo Hutchison - Branch Pontianak Branch-10'],
            [9,'Indosat Ooredoo Hutchison - Branch Pontianak Branch-4'],
            [9,'XL Axiata - GraPARI Pontianak Branch-3'],
            [9,'Warung Internet Branch-9 Pontianak'],
            [9,'XL Axiata - GraPARI Pontianak Branch-2'],
            [9,'Warung Internet Branch-3 Pontianak'],
            [9,'Indosat Ooredoo Hutchison - Branch Pontianak Branch-2'],
            [9,'Warung Internet Branch-5 Pontianak'],
            [9,'Provider Internet Lokal Branch-8 Pontianak'],
            [9,'Provider Internet Lokal Branch-4 Pontianak  site.co.id+1'],
            [9,'Indosat Ooredoo Hutchison - Branch Pontianak Branch-10'],
            [9,'XL Axiata - GraPARI Pontianak Branch-5  Facebook+1'],
            [9,'Telkomsel GraPARI Pontianak - Cabang Branch-4'],
            [9,'Provider Internet Lokal Branch-9 Pontianak'],
            [9,'Telkomsel GraPARI Pontianak - Cabang Branch-5'],
            [9,'Provider Internet Lokal Branch-5 Pontianak'],
            [9,'XL Axiata - GraPARI Pontianak Branch-2'],
            [9,'Telkomsel GraPARI Pontianak - Cabang Branch-4'],
            [9,'Telkomsel GraPARI Pontianak - Cabang Branch-3'],
            [9,'Telkomsel GraPARI Pontianak - Cabang Branch-5'],
            [9,'Provider Internet Lokal Branch-10 Pontianak'],
            [9,'Indosat Ooredoo Hutchison - Branch Pontianak Branch-7'],
            [9,'Indosat Ooredoo Hutchison - Branch Pontianak Branch-3  Facebook+1'],
            [9,'Telkomsel GraPARI Pontianak - Cabang Branch-10'],
            [9,'Warung Internet Branch-4 Pontianak']
        ];
        
        foreach($partnerships as $partnership)
        {
            CommunityPartnerships::firstOrCreate([
                'segments_id'=>$partnership[0],
                'name'=>$partnership[1]
            ]);
        }
    }
}
